### ISSUE TITLE
Possibility to switch context

### ISSUE THREAD

**Issue by jeromelefeuvre** [EddieRingle/hubroid#22]
Hi,

thanks for your app, I like it.

Do you think that should be possible to switch context ? I mean, I'm linked to my github company and I see company projects

Thanks and good luck !!

**Comment by eik3** [comment]
That would be great as I primarily use gh for company stuff.

**Comment by EddieRingle** [comment]
Organizations support is in the pipeline for 2.1. :-)

**Comment by EddieRingle** [comment]
Decided to make 2.0 as feature-rich as possible and have begun adding in Organization support. :)

**Comment by EddieRingle** [comment]
Considering this closed given the recent commits:

155b80e3802fffc2dff590dab2ca0decec857e5d
89e6baad185140f5033d2c01c74f97c0eb8e7ec4
c713c3f05f71580477b556887f8077028681fb16

Basic Organization functionality is implemented. I'll save further Teams and more advanced Organization features for a later date.

**Comment by mikofski** [comment]
**sweet!** I though it wasn't working, because it said there were zero repositories, but clicked on it anyway, and voila it's all there. But why did it say there were no repositories under my organization, when there are clearly more than zero. Also, and maybe this is another bug?, I don't think you can "follow" an "organization" on Github, but there is a "following/followers" section. Anyway, still great, thx!
