### ISSUE TITLE
Disapearing from market

### ISSUE THREAD

**Issue by proussille** [EddieRingle/hubroid#32]
Hello,

I bought the donate version and it disapear from the market.

Is it normal because I see it in SlideMe but can't redownload cause I bought it on market.

And i've some issues (FC) when checking CyanogenMod repos, so I want reinstall it. (but i can't)

I use cyanogenmod 7 (build 30 - 2.3.2).

Thx.

_pilip.

**Comment by EddieRingle** [comment]
Due to a hard drive failure, the keystore I used to publish apps was destroyed forever. Since then (a couple months ago), I have been working on 2.0.

Just yesterday I unpublished the old version from the Market and published 2.0-beta1. The new version is completely free with no ads, and I thank you for your previous donation.

Just do a search for Hubroid in the Market and you should see the new one. :-)

**Comment by proussille** [comment]
ok thank you.

And it's really a good work. gratz

**Comment by EddieRingle** [comment]
Thanks, hope you enjoy it.
