### ISSUE TITLE
API error in comment details in Public activity

### ISSUE THREAD

**Issue by nvdv** [EddieRingle/hubroid#66]
When I try get into details in my activity (StartUp Screen -> Profile -> Public Activity -> Comment Details), I get API error.
Here is screenshot:  http://i52.tinypic.com/2u8kqvm.png

**Comment by EddieRingle** [comment]
Yes, this is known. Unfortunately, the Activity feed gives very little useful information for many events. I've discussed this issue with @technoweenie and he is aware of the issue. The problem it seems is that when the data for an event type changes, all previous events of that type that have occurred must be updated as well (or something like that).

One solution is to make an extra API call using the Issue API to actually retrieve those comment details, but I'd rather not do that. It also appears that I can make use of the GitHub URL sent along with the event to link people to the issue itself, so that at least you have an easy way of getting to the issue to read the comment.

For any real solution though, we'll just have to wait for more help on GitHub's end.
